version: "3.12"

services:
  api:
    build:
      context: ../../
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge